# TOTVS service collector
# O template ZBX-TOTVS-PASSIVE usa esta coleta como item mestre.
UserParameter=totvs.service.collect[*],powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\totvs_monitor.ps1" COLLECT "$1"
