#requires -Version 5.1
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$Repo = $env:GITHUB_WORKSPACE
if ([string]::IsNullOrWhiteSpace($Repo)) { throw 'GITHUB_WORKSPACE ausente.' }
$Product = Join-Path $Repo 'windows\zabbix-agent-deployment'
$Version = '2.0.11'
$Tag = 'ddm-snoc-windows-v2.0.11'
$Utf8 = New-Object System.Text.UTF8Encoding($false)
function Read-DDMText([string]$Path) { [IO.File]::ReadAllText($Path) }
function Save-DDMText([string]$Path,[string]$Text) { [IO.File]::WriteAllText($Path,$Text,$Utf8) }
function Replace-DDMOnce([string]$Text,[string]$Old,[string]$New,[string]$Label) { if(-not $Text.Contains($Old)){throw "Trecho nao encontrado para ${Label}: $Old"};$Text.Replace($Old,$New) }
function Write-DDMCmd([string]$Name,[string[]]$Lines) { [IO.File]::WriteAllLines((Join-Path $Product ('templates\central\'+$Name)),$Lines,[Text.Encoding]::ASCII) }
function Invoke-DDMRobocopy([string]$Source,[string]$Destination) { New-Item $Destination -ItemType Directory -Force|Out-Null;& robocopy.exe $Source $Destination /E /COPY:DAT /DCOPY:DAT /R:2 /W:2 /XJ /SL /NP /NFL /NDL|Out-Host;if($LASTEXITCODE -gt 7){throw "Robocopy falhou: $LASTEXITCODE"} }

Write-Host '1/8 - Normalizando todos os CMDs centrais para UNC.' -ForegroundColor Cyan
$Prefix=@('@echo off','setlocal EnableExtensions DisableDelayedExpansion','set "CENTRAL=%~dp0"','if "%CENTRAL:~-1%"=="\" set "CENTRAL=%CENTRAL:~0,-1%"')
Write-DDMCmd 'INSTALAR-BOOTSTRAP.cmd' ($Prefix+@('set "INSTALLER=%CENTRAL%\BOOTSTRAP-INSTALL\bootstrap\Install-DDM-SNOC-Bootstrap.ps1"','if not exist "%INSTALLER%" exit /b 3','powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%INSTALLER%" -CentralRoot "%CENTRAL%"','exit /b %ERRORLEVEL%'))
Write-DDMCmd 'GPO-DIARIA.cmd' ($Prefix+@('set "BOOT=C:\ProgramData\BKPCloud\SNOC-Windows\Bootstrap\Invoke-DDM-SNOC-Bootstrap.ps1"','if not exist "%BOOT%" call "%CENTRAL%\INSTALAR-BOOTSTRAP.cmd"','if errorlevel 1 exit /b %ERRORLEVEL%','powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%BOOT%" -CentralRoot "%CENTRAL%" -Mode Auto','exit /b %ERRORLEVEL%'))
Write-DDMCmd 'INSTALAR.cmd' ($Prefix+@('set "BOOT=C:\ProgramData\BKPCloud\SNOC-Windows\Bootstrap\Invoke-DDM-SNOC-Bootstrap.ps1"','if not exist "%BOOT%" call "%CENTRAL%\INSTALAR-BOOTSTRAP.cmd"','if errorlevel 1 exit /b %ERRORLEVEL%','powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%BOOT%" -CentralRoot "%CENTRAL%" -Mode Apply -MaxJitterSeconds 0','exit /b %ERRORLEVEL%'))
Write-DDMCmd 'REPARAR.cmd' ($Prefix+@('set "BOOT=C:\ProgramData\BKPCloud\SNOC-Windows\Bootstrap\Invoke-DDM-SNOC-Bootstrap.ps1"','if not exist "%BOOT%" call "%CENTRAL%\INSTALAR-BOOTSTRAP.cmd"','if errorlevel 1 exit /b %ERRORLEVEL%','powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%BOOT%" -CentralRoot "%CENTRAL%" -Mode Repair -MaxJitterSeconds 0','exit /b %ERRORLEVEL%'))
Write-DDMCmd 'DIAGNOSTICAR.cmd' ($Prefix+@('set "BOOT=C:\ProgramData\BKPCloud\SNOC-Windows\Bootstrap\Invoke-DDM-SNOC-Bootstrap.ps1"','if not exist "%BOOT%" call "%CENTRAL%\INSTALAR-BOOTSTRAP.cmd"','if errorlevel 1 exit /b %ERRORLEVEL%','powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%BOOT%" -CentralRoot "%CENTRAL%" -Mode Diagnose -MaxJitterSeconds 0','exit /b %ERRORLEVEL%'))
Write-DDMCmd 'ATUALIZAR-AD.cmd' ($Prefix+@('set "UPDATER=%CENTRAL%\CENTRAL-UPDATER\central\Update-DDM-SNOC-Central.ps1"','set "LOG=%CENTRAL%\UPDATE-AD-TASK.log"','echo [%date% %time%] Inicio do update central >> "%LOG%"','if not exist "%CENTRAL%\CLIENTE.ps1" (','  echo [%date% %time%] ERRO: CLIENTE.ps1 nao encontrado em %CENTRAL% >> "%LOG%"','  exit /b 2',')','if not exist "%UPDATER%" (','  echo [%date% %time%] ERRO: atualizador fixo nao encontrado. Aplique primeiro o pacote AD-SEED oficial. >> "%LOG%"','  exit /b 3',')','"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "%UPDATER%" -CentralRoot "%CENTRAL%"','set "RC=%ERRORLEVEL%"','if "%RC%"=="0" (','  echo [%date% %time%] OK: update central concluido >> "%LOG%"',') else (','  echo [%date% %time%] ERRO: update central retornou %RC% >> "%LOG%"',')','exit /b %RC%'))
Write-DDMCmd 'VOLTAR-RELEASE.cmd' ($Prefix+@('set "SCRIPT=%CENTRAL%\CENTRAL-TOOLS\tools\Set-DDM-CentralRelease.ps1"','if not exist "%SCRIPT%" (','  echo ERRO: ferramenta de rollback nao encontrada: %SCRIPT%','  exit /b 2',')','if /I "%~1"=="PREVIOUS" (','  "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%" -CentralRoot "%CENTRAL%" -UsePrevious','  exit /b %ERRORLEVEL%',')','if not "%~1"=="" (','  "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%" -CentralRoot "%CENTRAL%" -ReleaseId "%~1"','  exit /b %ERRORLEVEL%',')','"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%" -CentralRoot "%CENTRAL%" -List','echo.','set /p "TARGET=Digite o ReleaseId ou PREVIOUS para cancelar a ultima troca: "','if /I "%TARGET%"=="PREVIOUS" (','  "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%" -CentralRoot "%CENTRAL%" -UsePrevious',') else (','  "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%" -CentralRoot "%CENTRAL%" -ReleaseId "%TARGET%"',')','exit /b %ERRORLEVEL%'))

Write-Host '2/8 - Promovendo versao, recuperador e documentacao.' -ForegroundColor Cyan
$ConfigPath=Join-Path $Product 'config\DDM-Product.ps1';$Config=Read-DDMText $ConfigPath;$Config=Replace-DDMOnce $Config "ProductVersion           = '2.0.10'" "ProductVersion           = '2.0.11'" 'ProductVersion';Save-DDMText $ConfigPath $Config
$RecoveryPath=Join-Path $Product 'tools\Recover-DDM-SNOC-Central.ps1';$Recovery=Read-DDMText $RecoveryPath;$Recovery=Replace-DDMOnce $Recovery "[string]`$ExpectedTag = 'ddm-snoc-windows-v2.0.10'" "[string]`$ExpectedTag = 'ddm-snoc-windows-v2.0.11'" 'ExpectedTag';Save-DDMText $RecoveryPath $Recovery
$TestPath=Join-Path $Product 'tools\Test-DDM-Repository.ps1';$Test=Read-DDMText $TestPath;$Test=Replace-DDMOnce $Test "Assert-DDMTest (`$DDMProduct.ProductVersion -eq '2.0.10') 'ProductVersion deve ser 2.0.10.'" "Assert-DDMTest (`$DDMProduct.ProductVersion -eq '2.0.11') 'ProductVersion deve ser 2.0.11.'" 'versao do teste';Save-DDMText $TestPath $Test
$ChangePath=Join-Path $Product 'CHANGELOG.md';$Change=Read-DDMText $ChangePath;if($Change -notmatch '(?m)^## 2\.0\.11\b'){Save-DDMText $ChangePath ("## 2.0.11 - 2026-08-04`r`n- Normaliza todos os sete CMDs centrais executados por caminho UNC.`r`n- Inclui update central, instalacao, reparo, diagnostico e rollback no teste SMB integral.`r`n- Impede passagem direta de %~dp0 com barra final ao PowerShell.`r`n`r`n"+$Change)}
$DocPath=Join-Path $Product 'docs\GPO-DIARIA.md';$Doc=Read-DDMText $DocPath;if($Doc -notmatch 'sete CMDs centrais'){Save-DDMText $DocPath ("## Cobertura integral dos CMDs por UNC`r`n`r`nO pipeline executa os sete CMDs centrais diretamente por SMB: instalacao do bootstrap, GPO diaria, instalacao, reparo, diagnostico, update do AD e rollback.`r`n`r`n"+$Doc)}

Write-Host '3/8 - Executando auditoria completa e teste SMB dos sete CMDs.' -ForegroundColor Cyan
& (Join-Path $Product 'tools\Test-DDM-Repository.ps1') -ProductRoot $Product
& (Join-Path $Product 'tools\Test-DDM-RuntimeLexing.ps1') -ProductRoot $Product
& (Join-Path $Product 'tools\Test-DDM-CentralBootstrapLoad.ps1') -ProductRoot $Product
& (Join-Path $Product 'tools\Test-DDM-AclValidation.ps1') -ProductRoot $Product

Write-Host '4/8 - Gravando fonte validada no main.' -ForegroundColor Cyan
foreach($Temp in @('.github\workflows\_promote-ddm-snoc-2.0.11.yml','windows\zabbix-agent-deployment\tools\Promote-DDM-SNOC-2.0.11.ps1')){Remove-Item -LiteralPath (Join-Path $Repo $Temp) -Force -ErrorAction SilentlyContinue}
Remove-Item -LiteralPath (Join-Path $Repo 'release-status\ddm-snoc-windows-v2.0.11.txt') -Force -ErrorAction SilentlyContinue
git config user.name 'github-actions[bot]';git config user.email '41898282+github-actions[bot]@users.noreply.github.com';git add -A;git diff --cached --quiet;if($LASTEXITCODE -eq 0){throw 'Nenhuma alteracao produzida.'};git commit -m 'fix(snoc-windows): normaliza todos os CMDs UNC e promove 2.0.11';git push origin HEAD:main;$SourceCommit=(git rev-parse HEAD).Trim()

Write-Host '5/8 - Construindo e validando assets imutaveis.' -ForegroundColor Cyan
$Dist=Join-Path $Repo 'dist-2.0.11';$Motor=Join-Path $Dist ("DDM-SNOC-WINDOWS-MOTOR-$Version");$Seed=Join-Path $Dist ("DDM-SNOC-WINDOWS-AD-SEED-$Version");Remove-Item $Dist -Recurse -Force -ErrorAction SilentlyContinue;New-Item $Motor,$Seed -ItemType Directory -Force|Out-Null
foreach($Name in @('Start-DDM-SNOC.ps1','CLIENTE.example.ps1','README.md','CHANGELOG.md')){Copy-Item (Join-Path $Product $Name) (Join-Path $Motor $Name) -Force}
foreach($Name in @('config','lib','central','bootstrap','endpoint','engine','modules','templates','tools','docs','clients')){Copy-Item (Join-Path $Product $Name) (Join-Path $Motor $Name) -Recurse -Force}
foreach($Name in @('ATUALIZAR-AD.cmd','VOLTAR-RELEASE.cmd')){Copy-Item (Join-Path $Product ('templates\central\'+$Name)) (Join-Path $Seed $Name) -Force}
Copy-Item (Join-Path $Product 'CLIENTE.example.ps1') (Join-Path $Seed 'CLIENTE.example.ps1') -Force;Copy-Item (Join-Path $Product 'docs\UPDATE-AD.md') (Join-Path $Seed 'LEIA-ME-UPDATE-AD.md') -Force;Copy-Item (Join-Path $Product 'docs\AUDITORIA-300-PONTOS.md') (Join-Path $Seed 'AUDITORIA-300-PONTOS.md') -Force;Copy-Item (Join-Path $Product 'docs\AUDITORIA-MIZU-ACL-40-PONTOS.md') (Join-Path $Seed 'AUDITORIA-MIZU-ACL-40-PONTOS.md') -Force
$Updater=Join-Path $Seed 'CENTRAL-UPDATER';foreach($Rel in @('central\Update-DDM-SNOC-Central.ps1','central\lib\DDM-Central-Client.ps1','central\lib\DDM-Central-Supply.ps1','central\lib\Invoke-DDM-Central-Publish.ps1','config\DDM-Product.ps1','lib\DDM-Common.ps1')){$Dest=Join-Path $Updater $Rel;New-Item (Split-Path -Parent $Dest) -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $Product $Rel) $Dest -Force}
$Rollback=Join-Path $Seed 'CENTRAL-TOOLS\tools\Set-DDM-CentralRelease.ps1';New-Item (Split-Path -Parent $Rollback) -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $Product 'tools\Set-DDM-CentralRelease.ps1') $Rollback -Force
$MotorZip=Join-Path $Dist ("DDM-SNOC-WINDOWS-MOTOR-$Version.zip");$SeedZip=Join-Path $Dist ("DDM-SNOC-WINDOWS-AD-SEED-$Version.zip");Compress-Archive -Path $Motor -DestinationPath $MotorZip -CompressionLevel Optimal;Compress-Archive -Path (Join-Path $Seed '*') -DestinationPath $SeedZip -CompressionLevel Optimal
$ExpandedZip=Join-Path $env:RUNNER_TEMP 'ddm-211-zip';$ExpandedRepo=Join-Path $env:RUNNER_TEMP 'ddm-211-repo';Remove-Item $ExpandedZip,$ExpandedRepo -Recurse -Force -ErrorAction SilentlyContinue;Expand-Archive $MotorZip $ExpandedZip -Force;$ExpandedSource=Join-Path $ExpandedZip ("DDM-SNOC-WINDOWS-MOTOR-$Version");$ExpandedProduct=Join-Path $ExpandedRepo 'windows\zabbix-agent-deployment';New-Item (Split-Path -Parent $ExpandedProduct) -ItemType Directory -Force|Out-Null;Invoke-DDMRobocopy $ExpandedSource $ExpandedProduct;$WF=Join-Path $ExpandedRepo '.github\workflows';New-Item $WF -ItemType Directory -Force|Out-Null;foreach($N in @('ddm-snoc-windows-validation.yml','ddm-snoc-windows-release.yml')){Copy-Item (Join-Path $Repo ('.github\workflows\'+$N)) (Join-Path $WF $N) -Force}
& (Join-Path $ExpandedProduct 'tools\Test-DDM-Repository.ps1') -ProductRoot $ExpandedProduct;& (Join-Path $ExpandedProduct 'tools\Test-DDM-RuntimeLexing.ps1') -ProductRoot $ExpandedProduct;& (Join-Path $ExpandedProduct 'tools\Test-DDM-CentralBootstrapLoad.ps1') -ProductRoot $ExpandedProduct;& (Join-Path $ExpandedProduct 'tools\Test-DDM-AclValidation.ps1') -ProductRoot $ExpandedProduct
$Assets=@();foreach($Zip in @($MotorZip,$SeedZip)){$H=(Get-FileHash $Zip -Algorithm SHA256).Hash;Set-Content ($Zip+'.sha256') ($H+' *'+(Split-Path -Leaf $Zip)) -Encoding ASCII;$Assets+=New-Object PSObject -Property @{Name=(Split-Path -Leaf $Zip);Sha256=$H;Size=(Get-Item $Zip).Length}}
$ManifestPath=Join-Path $Dist ("DDM-SNOC-WINDOWS-RELEASE-MANIFEST-$Version.json");$Manifest=New-Object PSObject -Property @{Product='DDM SNOC Windows';ProductVersion=$Version;GitCommit=$SourceCommit;GitTag=$Tag;GeneratedAtUtc=(Get-Date).ToUniversalTime().ToString('o');Assets=$Assets;Validation=@('repository','all-official-clients','all-seven-unc-cmds','expanded-motor','full-central-pilot');ExternalPilotsRequired=$false};$Manifest|ConvertTo-Json -Depth 6|Set-Content $ManifestPath -Encoding UTF8;$MH=(Get-FileHash $ManifestPath -Algorithm SHA256).Hash;Set-Content ($ManifestPath+'.sha256') ($MH+' *'+(Split-Path -Leaf $ManifestPath)) -Encoding ASCII

Write-Host '6/8 - Criando release oficial 2.0.11.' -ForegroundColor Cyan
if(-not [string]::IsNullOrWhiteSpace([string](git ls-remote --tags origin "refs/tags/$Tag"))){& gh release delete $Tag --yes 2>$null;git push --delete origin $Tag};git tag -a $Tag $SourceCommit -m "DDM SNOC Windows $Version";git push origin $Tag;$Files=@($MotorZip,($MotorZip+'.sha256'),$SeedZip,($SeedZip+'.sha256'),$ManifestPath,($ManifestPath+'.sha256'));& gh release create $Tag @Files --verify-tag --target $SourceCommit --title "DDM SNOC Windows $Version" --notes 'Normaliza todos os CMDs centrais por UNC e valida os sete fluxos em SMB real.';if($LASTEXITCODE -ne 0){throw "gh release create retornou $LASTEXITCODE"}

Write-Host '7/8 - Executando piloto integral do atualizador central.' -ForegroundColor Cyan
$PilotRoot=Join-Path 'C:\' ('DDM-SNOC-E2E-211-'+[guid]::NewGuid().ToString('N'));$Central=Join-Path $PilotRoot 'ZBX';try{New-Item $Central -ItemType Directory -Force|Out-Null;& icacls.exe $Central /inheritance:r|Out-Host;if($LASTEXITCODE -ne 0){throw 'Falha ACL piloto.'};& icacls.exe $Central /grant:r '*S-1-5-18:(OI)(CI)F' '*S-1-5-32-544:(OI)(CI)F' '*S-1-5-11:(OI)(CI)RX'|Out-Host;if($LASTEXITCODE -ne 0){throw 'Falha ACL piloto.'};Expand-Archive $SeedZip $Central -Force;$PilotClient=Join-Path $Central 'CLIENTE.ps1';$Client=Read-DDMText (Join-Path $Product 'clients\AGL\CLIENTE.ps1');Save-DDMText $PilotClient ($Client.Replace('\\mizu.local\NETLOGON\SCRIPTS\ZBX',$Central));Start-Sleep 5;$U=Join-Path $Central 'CENTRAL-UPDATER\central\Update-DDM-SNOC-Central.ps1';& powershell.exe -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $U -CentralRoot $Central;if($LASTEXITCODE -ne 0){throw "Piloto retornou $LASTEXITCODE"};$Current=(Get-Content (Join-Path $Central 'CURRENT.txt') -First 1).Trim();if($Current -notlike "$Version`__*"){throw "CURRENT inesperado: $Current"};Write-Host "FULL_CENTRAL_PILOT_OK $Current" -ForegroundColor Green}catch{& gh release delete $Tag --yes 2>$null;git push --delete origin $Tag 2>$null;throw}finally{Remove-Item $PilotRoot -Recurse -Force -ErrorAction SilentlyContinue}

Write-Host '8/8 - Registrando READY.' -ForegroundColor Cyan
Remove-Item $Dist,$ExpandedZip,$ExpandedRepo -Recurse -Force -ErrorAction SilentlyContinue;git fetch origin main;git checkout -B evidence origin/main;$Status=Join-Path $Repo 'release-status\ddm-snoc-windows-v2.0.11.txt';Set-Content $Status ('State=READY Tag='+$Tag+' Commit='+$SourceCommit+' Assets=6 AllSevenUncCmds=PASS FullCentralPilot=PASS VerifiedAtUtc='+(Get-Date).ToUniversalTime().ToString('o')) -Encoding UTF8;git add $Status;git commit -m 'chore(snoc-windows): registra release 2.0.11 validada';git push origin HEAD:main;Write-Host 'DDM_SNOC_2_0_11_READY' -ForegroundColor Green
