$CentralLeasePath=$null
$CentralLeaseOwned=$false
$OwnerCreated=$false

function Enter-DDMCentralLease {
    $script:CentralLeasePath=Join-Path $CentralRoot $DDMProduct.CentralLockFile
    $LeaseMinutes=[int]$DDMProduct.CentralLockLeaseMinutes;if($LeaseMinutes -lt 15){$LeaseMinutes=180}
    for($Attempt=1;$Attempt -le 2;$Attempt++){
        try{
            $Stream=New-Object IO.FileStream($script:CentralLeasePath,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::Read)
            try{$Payload=@{Product=$DDMProduct.ProductCode;Mode='CENTRAL_UPDATE';Computer=$env:COMPUTERNAME;ProcessId=$PID;StartedAtUtc=(Get-Date).ToUniversalTime().ToString('o');ExpiresAtUtc=(Get-Date).ToUniversalTime().AddMinutes($LeaseMinutes).ToString('o')}|ConvertTo-Json -Compress;$Bytes=[Text.Encoding]::UTF8.GetBytes($Payload);$Stream.Write($Bytes,0,$Bytes.Length);$Stream.Flush()}finally{$Stream.Dispose()}
            $script:CentralLeaseOwned=$true;Write-CentralLog("Lease central adquirido: "+$script:CentralLeasePath)'OK';return
        }catch[IO.IOException]{
            if(-not(Test-Path $script:CentralLeasePath)){continue};$Expired=$false
            try{$Existing=Get-Content $script:CentralLeasePath -Raw|ConvertFrom-Json;$Expired=[datetime]::Parse([string]$Existing.ExpiresAtUtc).ToUniversalTime() -lt (Get-Date).ToUniversalTime();if(-not$Expired){throw"Outra atualizacao central esta ativa em $($Existing.Computer), PID=$($Existing.ProcessId)."}}
            catch{if($_.Exception.Message -like'Outra atualizacao central esta ativa*'){throw};$Expired=((Get-Date)-(Get-Item $script:CentralLeasePath).LastWriteTime).TotalMinutes -gt $LeaseMinutes;if(-not$Expired){throw'Lock central invalido e ainda dentro da janela de seguranca.'}}
            if($Expired){Write-CentralLog'Lease central expirado removido.' 'WARN';Remove-Item $script:CentralLeasePath -Force;continue}
        }
    }
    throw'Nao foi possivel adquirir lease central.'
}
function Exit-DDMCentralLease{if($script:CentralLeaseOwned){Remove-Item $script:CentralLeasePath -Force -ErrorAction SilentlyContinue;$script:CentralLeaseOwned=$false}}

function Get-DDMSafeCentralPath([string]$Relative,[string]$Label){if([string]::IsNullOrWhiteSpace($Relative) -or [IO.Path]::IsPathRooted($Relative) -or $Relative -match'(^|[\\/])\.\.([\\/]|$)'){throw"$Label invalido: $Relative"};$Base=[IO.Path]::GetFullPath($CentralRoot).TrimEnd('\')+'\';$Full=[IO.Path]::GetFullPath((Join-Path $CentralRoot $Relative));if(-not$Full.ToLowerInvariant().StartsWith($Base.ToLowerInvariant())){throw"$Label escapa da central: $Relative"};return$Full}
function Test-DDMEmergencyBlock([string]$ReleaseId,[string]$ProductVersion,[string]$AgentVersion){$Path=Join-Path $CentralRoot $DDMProduct.EmergencyBlockFile;if(-not(Test-Path $Path)){return};foreach($Line in @(Get-Content $Path)){$Rule=([string]$Line).Trim();if([string]::IsNullOrWhiteSpace($Rule) -or $Rule.StartsWith('#')){continue};if(@('ALL',$ReleaseId,$ProductVersion,$AgentVersion) -contains $Rule){throw"Release bloqueada administrativamente por $Path: $Rule"}}}
function Write-DDMCentralStatus([string]$State,[string]$Message,[string]$ReleaseId='',[string]$AgentVersion=''){try{$Status=@{Product=$DDMProduct.ProductCode;State=$State;Message=$Message;ReleaseId=$ReleaseId;ProductVersion=[string]$DDMProduct.ProductVersion;AgentVersion=$AgentVersion;Computer=$env:COMPUTERNAME;UpdatedAtUtc=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Depth 5;Write-DDMAtomicText (Join-Path $CentralRoot $DDMProduct.ProductStatusFile) ($Status+"`r`n") 'UTF8'}catch{}}

function Assert-DDMCentralOwner($Client){
    $OwnerPath=Join-Path $CentralRoot $DDMProduct.CentralOwnerFile;$Expected='DDM-SNOC-WINDOWS|'+[string]$Client.ClientId
    if(Test-Path $OwnerPath){if((Read-DDMFirstLine $OwnerPath) -ne $Expected){throw'Pasta central pertence a outro produto ou cliente.'};return}
    $ExistingState=@($DDMProduct.CurrentVersionFile,$DDMProduct.CentralMotorFolder,$DDMProduct.CentralReleaseFolder|ForEach-Object{Join-Path $CentralRoot $_}|Where-Object{Test-Path $_})
    if($ExistingState.Count -gt 0){throw'Marcador de propriedade ausente em central que ja possui estado do produto.'}
    Write-DDMAtomicText $OwnerPath ($Expected+"`r`n") 'ASCII';$script:OwnerCreated=$true
}

function Get-DDMReleaseInfo([string]$ReleaseBase,[string]$ReleaseId){
    if([string]::IsNullOrWhiteSpace($ReleaseId) -or $ReleaseId -notmatch'^[A-Za-z0-9._+-]+$'){throw"ReleaseId invalido: $ReleaseId"};$Root=Join-Path $ReleaseBase $ReleaseId;$Ready=Join-Path $Root $DDMProduct.ReleaseReadyFile;$ManifestPath=Join-Path $Root $DDMProduct.ReleaseManifestFile;$Runtime=Join-Path $Root $DDMProduct.ClientRuntimeFile
    if(-not(Test-Path $Ready) -or -not(Test-Path $ManifestPath) -or -not(Test-Path $Runtime)){throw"Release incompleta: $ReleaseId"};$ReadyText=Read-DDMFirstLine $Ready;if($ReadyText -notmatch'^READY\s+(?<id>\S+)\s+(?<hash>[0-9A-Fa-f]{64})$' -or $Matches['id'] -ne $ReleaseId){throw"READY invalido: $ReleaseId"};if((Get-DDMSha256 $ManifestPath) -ne $Matches['hash'].ToUpperInvariant()){throw"Manifesto de release divergente: $ReleaseId"}
    $Info=Import-DDMClixmlSafe $ManifestPath;if([string]$Info.ReleaseId -ne $ReleaseId -or [string]$Info.ProductName -ne [string]$DDMProduct.ProductName){throw"Identidade de release invalida: $ReleaseId"};if([string]$Info.ClientRuntimeSha256 -ne (Get-DDMSha256 $Runtime)){throw"Runtime da release divergente: $ReleaseId"};return$Info
}

function Publish-DDMActiveControls([string]$ReleaseBase,[string]$ReleaseId){
    $Info=Get-DDMReleaseInfo $ReleaseBase $ReleaseId;$ReleaseRoot=Join-Path $ReleaseBase $ReleaseId;$Client=Import-DDMClixmlSafe (Join-Path $ReleaseRoot $DDMProduct.ClientRuntimeFile);$MotorRoot=Get-DDMSafeCentralPath ([string]$Info.MotorRelativePath)'MotorRelativePath'
    Publish-DDMFixedDirectory $MotorRoot (Join-Path $CentralRoot 'CENTRAL-UPDATER') @('central\Update-DDM-SNOC-Central.ps1','central\lib\DDM-Central-Client.ps1','central\lib\DDM-Central-Supply.ps1','central\lib\Invoke-DDM-Central-Publish.ps1','config\DDM-Product.ps1','lib\DDM-Common.ps1')
    Publish-DDMFixedDirectory $MotorRoot (Join-Path $CentralRoot 'BOOTSTRAP-INSTALL') @('bootstrap\Install-DDM-SNOC-Bootstrap.ps1','bootstrap\Invoke-DDM-SNOC-Bootstrap.ps1','config\DDM-Product.ps1','lib\DDM-Common.ps1')
    Publish-DDMFixedDirectory $MotorRoot (Join-Path $CentralRoot 'CENTRAL-TOOLS') @('tools\Set-DDM-CentralRelease.ps1')
    $Templates=Join-Path $MotorRoot 'templates\central';if(Test-Path $Templates){foreach($File in @(Get-ChildItem $Templates|Where-Object{-not$_.PSIsContainer})){if($File.Name -eq'GPO-DIARIA.cmd'){continue};Publish-DDMFixedFile $File.FullName (Join-Path $CentralRoot $File.Name)}}
    $GpoDestination=Join-Path $CentralRoot 'GPO-DIARIA.cmd'
    if([string]$Client.Update.EndpointMode -eq'LOCAL_BOOTSTRAP_SCHEDULED_TASK'){$GpoSource=Join-Path $Templates 'GPO-DIARIA.cmd';if(-not(Test-Path $GpoSource)){throw'Release automatizada sem GPO-DIARIA.cmd.'};Publish-DDMFixedFile $GpoSource $GpoDestination}else{Remove-Item $GpoDestination -Force -ErrorAction SilentlyContinue}
}

function Rotate-DDMCentralLog{if(Test-Path $LogPath){$Info=Get-Item $LogPath;if($Info.Length -gt 20MB){$Archive=$LogPath+'.'+(Get-Date -Format'yyyyMMdd-HHmmss');Move-Item $LogPath $Archive -Force};$Cutoff=(Get-Date).AddDays(-[int]$DDMProduct.KeepLogDays);foreach($Old in @(Get-ChildItem (Split-Path -Parent $LogPath)|Where-Object{-not$_.PSIsContainer -and $_.Name -like((Split-Path -Leaf $LogPath)+'.*') -and $_.LastWriteTime -lt $Cutoff})){Remove-Item $Old.FullName -Force -ErrorAction SilentlyContinue}}}

try{
    $Locked=$Mutex.WaitOne(0,$false);if(-not$Locked){throw'Outra atualizacao central local ja esta em execucao.'};New-Item $RunRoot -ItemType Directory -Force|Out-Null;New-Item $CentralRoot -ItemType Directory -Force|Out-Null
    if(-not[string]::IsNullOrWhiteSpace($MotorSourceRoot)){$SourceRoot=(Resolve-Path $MotorSourceRoot).Path;Write-CentralLog"Usando motor local: $SourceRoot"'WARN'}else{$Extract=Join-Path $RunRoot 'motor';New-Item $Extract -ItemType Directory -Force|Out-Null;$BootstrapProduct=@{RepositoryReleaseApiUrl='https://api.github.com/repos/bkpcloud-app/snoc/releases?per_page=100';RepositoryAssetPattern='^DDM-SNOC-WINDOWS-MOTOR-[0-9]+\.[0-9]+\.[0-9]+\.zip$';HttpTimeoutSeconds=120;MaxDownloadSizeMB=1024};$SourceRoot=Get-MotorFromLatestRelease $BootstrapProduct $Extract}
    $ProductPath=Join-Path $SourceRoot 'config\DDM-Product.ps1';if(-not(Test-Path $ProductPath)){throw'DDM-Product.ps1 ausente no motor.'};. $ProductPath;. (Join-Path $SourceRoot 'lib\DDM-Common.ps1');Enter-DDMCentralLease;Rotate-DDMCentralLog;Write-DDMCentralStatus'RUNNING''Atualizacao central iniciada.'

    $ClientPath=Join-Path $CentralRoot $DDMProduct.ClientConfigFile;if(-not(Test-Path $ClientPath)){throw"CLIENTE.ps1 ausente em $CentralRoot"};if($CentralRoot -notlike'\\*' -and (Get-DDMFreeSpaceMB $CentralRoot) -lt [int]$DDMProduct.MinimumFreeSpaceMB){throw'Espaco livre insuficiente.'};if(-not$SkipAclValidation){Assert-DDMCentralAcl $CentralRoot;Assert-DDMCentralAcl $ClientPath;Assert-DDMShareAcl $CentralRoot}
    $ClientSourceHash=Get-DDMSha256 $ClientPath;$Client=Read-DDMClientPs1Safe $ClientPath;Assert-DDMClient $Client $DDMProduct;Assert-DDMCentralOwner $Client
    if(-not$SkipCentralPathValidation){$Declared=[IO.Path]::GetFullPath([string]$Client.Update.CentralPath).TrimEnd('\');if($Declared.ToLowerInvariant() -ne $CentralRoot.TrimEnd('\').ToLowerInvariant()){throw"CentralRoot divergente. Declarado=$Declared; executado=$CentralRoot"}}
    if(@('PILOT_READY','PILOT_READY_AFTER_ACL','PRODUCTION_READY') -notcontains [string]$Client.Status -and -not$AllowBlockedClient){throw"Cliente nao liberado: $($Client.Status). $(@($Client.Blockers)-join' | ')"}
    $RuntimeTemp=Join-Path $RunRoot $DDMProduct.ClientRuntimeFile;$Client|Export-Clixml $RuntimeTemp -Depth 12;$RuntimeHash=Get-DDMSha256 $RuntimeTemp

    $MotorBase=Join-Path $CentralRoot $DDMProduct.CentralMotorFolder;$VersionRoot=Join-Path $MotorBase $DDMProduct.ProductVersion;$MotorStage=Join-Path $MotorBase ('.staging-'+$env:COMPUTERNAME+'-'+[guid]::NewGuid().ToString('N'));New-Item $MotorBase -ItemType Directory -Force|Out-Null
    if(Test-Path $VersionRoot){$MotorManifestPath=Join-Path $VersionRoot $DDMProduct.MotorManifestFile;$MotorManifest=@(Import-DDMClixmlSafe $MotorManifestPath);Assert-DDMDirectoryMatchesManifest $VersionRoot $MotorManifest'motor publicado'$MotorManifestPath}
    else{New-Item $MotorStage -ItemType Directory -Force|Out-Null;foreach($Name in @('Start-DDM-SNOC.ps1','CLIENTE.example.ps1','README.md','CHANGELOG.md')){Copy-Item (Join-Path $SourceRoot $Name) (Join-Path $MotorStage $Name) -Force};foreach($Name in @('config','lib','central','bootstrap','endpoint','engine','modules','templates','tools','docs')){Copy-Item (Join-Path $SourceRoot $Name) (Join-Path $MotorStage $Name) -Recurse -Force};if(Test-Path (Join-Path $MotorStage 'base-package')){throw'base-package legado encontrado.'};$MotorManifest=New-DDMDirectoryManifest $MotorStage;$MotorManifestPath=Join-Path $MotorStage $DDMProduct.MotorManifestFile;Export-DDMClixmlAtomic $MotorManifest $MotorManifestPath 8;Assert-DDMDirectoryMatchesManifest $MotorStage $MotorManifest'motor em staging'$MotorManifestPath;Move-Item $MotorStage $VersionRoot;$MotorManifestPath=Join-Path $VersionRoot $DDMProduct.MotorManifestFile}

    $AgentVersion=Get-LatestZabbixVersion $DDMProduct.ZabbixCdnRoot;$ArtifactsBase=Join-Path $CentralRoot $DDMProduct.CentralArtifactsFolder;$ArtifactsRoot=Join-Path $ArtifactsBase $AgentVersion;$ArtifactStage=$ArtifactsRoot+'.staging-'+$env:COMPUTERNAME+'-'+[guid]::NewGuid().ToString('N')
    if(-not(Test-Path $ArtifactsRoot)){if($SkipArtifacts){throw"Artefatos $AgentVersion ausentes."};New-Item $ArtifactStage -ItemType Directory -Force|Out-Null;$Base=$DDMProduct.ZabbixCdnRoot.TrimEnd('/')+'/'+$AgentVersion;$Defs=@(@{Role='AGENT1_AMD64';Name="zabbix_agent-$AgentVersion-windows-amd64-openssl.msi"},@{Role='AGENT1_X86';Name="zabbix_agent-$AgentVersion-windows-i386-openssl.msi"},@{Role='AGENT2_AMD64';Name="zabbix_agent2-$AgentVersion-windows-amd64-openssl.msi"},@{Role='PLUGINS_AMD64';Name="zabbix_agent2_plugins-$AgentVersion-windows-amd64.msi"});$ArtifactItems=@();foreach($Def in $Defs){$Item=Sync-ZabbixArtifact ($Base+'/'+$Def.Name) $Def.Name $ArtifactStage $DDMProduct.ExpectedZabbixSigner;$Item|Add-Member NoteProperty Role $Def.Role;$Item|Add-Member NoteProperty Version $AgentVersion;$ArtifactItems+=$Item};$ArtifactManifestPath=Join-Path $ArtifactStage $DDMProduct.ArtifactManifestFile;Export-DDMClixmlAtomic $ArtifactItems $ArtifactManifestPath 6;Assert-DDMDirectoryMatchesManifest $ArtifactStage $ArtifactItems'artefatos em staging'$ArtifactManifestPath;Move-Item $ArtifactStage $ArtifactsRoot}
    $ArtifactManifestPath=Join-Path $ArtifactsRoot $DDMProduct.ArtifactManifestFile;$ArtifactItems=@(Import-DDMClixmlSafe $ArtifactManifestPath);Assert-DDMDirectoryMatchesManifest $ArtifactsRoot $ArtifactItems'artefatos publicados'$ArtifactManifestPath;foreach($Item in $ArtifactItems){Test-DDMAuthenticodeStrong (Join-Path $ArtifactsRoot ([string]$Item.Name)) $DDMProduct.ExpectedZabbixSigner}

    $MotorManifestPath=Join-Path $VersionRoot $DDMProduct.MotorManifestFile;$MotorHash=Get-DDMSha256 $MotorManifestPath;$ArtifactHash=Get-DDMSha256 $ArtifactManifestPath;$ReleaseId=('{0}__{1}__{2}'-f$DDMProduct.ProductVersion,$AgentVersion,$ClientSourceHash.Substring(0,24)).Replace('+','_');Test-DDMEmergencyBlock $ReleaseId $DDMProduct.ProductVersion $AgentVersion
    $ReleaseBase=Join-Path $CentralRoot $DDMProduct.CentralReleaseFolder;$ReleaseRoot=Join-Path $ReleaseBase $ReleaseId;$ReleaseStage=Join-Path $ReleaseBase ('.staging-'+$env:COMPUTERNAME+'-'+[guid]::NewGuid().ToString('N'));New-Item $ReleaseBase -ItemType Directory -Force|Out-Null
    if(Test-Path $ReleaseRoot){$Existing=Get-DDMReleaseInfo $ReleaseBase $ReleaseId;if([string]$Existing.ClientSourceSha256 -ne $ClientSourceHash -or [string]$Existing.MotorManifestSha256 -ne $MotorHash -or [string]$Existing.ArtifactManifestSha256 -ne $ArtifactHash){throw"Release publicada foi alterada: $ReleaseId"}}
    else{New-Item $ReleaseStage -ItemType Directory -Force|Out-Null;Copy-Item $RuntimeTemp (Join-Path $ReleaseStage $DDMProduct.ClientRuntimeFile) -Force;Write-DDMAtomicText (Join-Path $ReleaseStage $DDMProduct.ClientRuntimeHashFile) ($RuntimeHash+"`r`n")'ASCII';$Manifest=@{ReleaseId=$ReleaseId;ProductName=$DDMProduct.ProductName;ProductVersion=$DDMProduct.ProductVersion;ClientId=[string]$Client.ClientId;ClientConfigVersion=[string]$Client.ConfigVersion;ClientSourceSha256=$ClientSourceHash;ClientRuntimeSha256=$RuntimeHash;AgentVersion=$AgentVersion;MotorManifestSha256=$MotorHash;ArtifactManifestSha256=$ArtifactHash;PublishedAt=(Get-Date).ToUniversalTime().ToString('o');State='PUBLISHED_NOT_PILOTED';MotorRelativePath=($DDMProduct.CentralMotorFolder+'\'+$DDMProduct.ProductVersion);ArtifactsRelativePath=($DDMProduct.CentralArtifactsFolder+'\'+$AgentVersion)}; $ManifestPath=Join-Path $ReleaseStage $DDMProduct.ReleaseManifestFile;Export-DDMClixmlAtomic $Manifest $ManifestPath 5;Write-DDMAtomicText (Join-Path $ReleaseStage $DDMProduct.ReleaseReadyFile) ("READY $ReleaseId $(Get-DDMSha256 $ManifestPath)`r`n")'ASCII';Move-Item $ReleaseStage $ReleaseRoot}

    $CurrentPath=Join-Path $CentralRoot $DDMProduct.CurrentVersionFile;$PreviousPath=Join-Path $CentralRoot $DDMProduct.PreviousVersionFile;$RollbackPath=Join-Path $CentralRoot $DDMProduct.RollbackRequestFile;$PreviousRelease=Read-DDMFirstLine $CurrentPath
    if(-not[string]::IsNullOrWhiteSpace($PreviousRelease) -and -not$AllowDowngrade){$PreviousInfo=Get-DDMReleaseInfo $ReleaseBase $PreviousRelease;if((Compare-DDMSemVer $DDMProduct.ProductVersion ([string]$PreviousInfo.ProductVersion)) -lt 0){throw"Downgrade bloqueado: $($PreviousInfo.ProductVersion) -> $($DDMProduct.ProductVersion)"}}
    $RollbackActive=$false;if(Test-Path $RollbackPath){try{$Request=Import-DDMClixmlSafe $RollbackPath;$Expires=[datetime]::Parse([string]$Request.ExpiresAtUtc).ToUniversalTime();if([string]$Request.State -eq'AUTHORIZED' -and $Expires -gt (Get-Date).ToUniversalTime() -and [string]$Request.TargetReleaseId -eq $PreviousRelease){$RollbackActive=$true}else{Remove-Item $RollbackPath -Force}}catch{Remove-Item $RollbackPath -Force -ErrorAction SilentlyContinue}}
    $ActiveRelease=$PreviousRelease;if(-not$RollbackActive){if(-not[string]::IsNullOrWhiteSpace($PreviousRelease) -and $PreviousRelease -ne $ReleaseId){Write-DDMAtomicText $PreviousPath ($PreviousRelease+"`r`n")'ASCII'};Write-DDMAtomicText $CurrentPath ($ReleaseId+"`r`n")'ASCII';$ActiveRelease=$ReleaseId;Remove-Item $RollbackPath -Force -ErrorAction SilentlyContinue};if([string]::IsNullOrWhiteSpace($ActiveRelease)){$ActiveRelease=$ReleaseId};Publish-DDMActiveControls $ReleaseBase $ActiveRelease

    $Keep=if($Client.Update.KeepMotorVersions){[int]$Client.Update.KeepMotorVersions}else{[int]$DDMProduct.KeepCentralVersions};$Cutoff=(Get-Date).AddDays(-7);$Releases=@(Get-ChildItem $ReleaseBase|Where-Object{$_.PSIsContainer -and $_.Name -notlike'.staging-*'}|Sort-Object LastWriteTime -Descending);$KeepIds=@($ReleaseId,$PreviousRelease,$ActiveRelease)+@($Releases|Select-Object -First $Keep|ForEach-Object{$_.Name});$KeepIds=@($KeepIds|Where-Object{$_}|Sort-Object -Unique);foreach($Old in $Releases){if($KeepIds -notcontains $Old.Name -and $Old.LastWriteTime -lt $Cutoff){Remove-Item $Old.FullName -Recurse -Force}}
    $Message="Atualizacao concluida. Publicada=$ReleaseId; Ativa=$ActiveRelease; Motor=$($DDMProduct.ProductVersion); Zabbix=$AgentVersion; Cliente=$($Client.ClientId)";Write-DDMCentralStatus'OK'$Message $ActiveRelease $AgentVersion;Write-CentralLog $Message'OK';exit 0
}catch{try{Write-DDMCentralStatus'ERROR'$_.Exception.Message}catch{};try{Write-CentralLog $_.Exception.Message'ERROR'}catch{};if($OwnerCreated){Remove-Item (Join-Path $CentralRoot $DDMProduct.CentralOwnerFile) -Force -ErrorAction SilentlyContinue};throw}
finally{
    $Stale=(Get-Date).AddHours(-[int]$DDMProduct.StaleStagingHours);foreach($Base in @((Join-Path $CentralRoot 'MOTOR'),(Join-Path $CentralRoot 'ARTIFACTS'),(Join-Path $CentralRoot 'RELEASES'))){if(Test-Path $Base){foreach($Item in @(Get-ChildItem $Base -ErrorAction SilentlyContinue|Where-Object{$_.PSIsContainer -and $_.Name -like'.staging-*'})){if($Item.Name -like('.staging-'+$env:COMPUTERNAME+'-*') -or $Item.LastWriteTime -lt $Stale){Remove-Item $Item.FullName -Recurse -Force -ErrorAction SilentlyContinue}}}}
    Remove-Item $RunRoot -Recurse -Force -ErrorAction SilentlyContinue;Exit-DDMCentralLease;if($Locked){try{$Mutex.ReleaseMutex()}catch{}};$Mutex.Close()
}
