### VEEAM - Zabbix Agent 2
### Script original: zabbix_vbr_job.ps1
### Caminho padrao: C:\Program Files\Zabbix Agent 2\scripts

UserParameter=vbr[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\zabbix_vbr_job.ps1" "$1" "$2" "$3"

AllowKey=system.run[powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\zabbix_vbr_job.ps1" ExportXml,nowait]
